version: '3.5'
services:
  web:
    container_name: web_app_react
    restart: always
    volumes:
      - .:/app
    build: .
    command: "sh start.sh"
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
